volumes:
  mongodb_volume:

services:
  backend:
    build: backend/
    restart: always
    ports:
    - 6000:6000

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
    - mongodb_volume:/data/db
    ports:
        - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
